//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.10 at 11:50:22 AM CET 
//


package it.polito.dp2.NFFG.sol3.service.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.NFFG.sol3.service.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.NFFG.sol3.service.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nffgs }
     * 
     */
    public Nffgs createNffgs() {
        return new Nffgs();
    }

    /**
     * Create an instance of {@link Policies }
     * 
     */
    public Policies createPolicies() {
        return new Policies();
    }

    /**
     * Create an instance of {@link it.polito.dp2.NFFG.sol3.service.jaxb.Nffg }
     * 
     */
    public it.polito.dp2.NFFG.sol3.service.jaxb.Nffg createNffg() {
        return new it.polito.dp2.NFFG.sol3.service.jaxb.Nffg();
    }

    /**
     * Create an instance of {@link Nffgs.Nffg }
     * 
     */
    public Nffgs.Nffg createNffgsNffg() {
        return new Nffgs.Nffg();
    }

    /**
     * Create an instance of {@link Policies.Policy }
     * 
     */
    public Policies.Policy createPoliciesPolicy() {
        return new Policies.Policy();
    }

    /**
     * Create an instance of {@link it.polito.dp2.NFFG.sol3.service.jaxb.Nffg.Nodes }
     * 
     */
    public it.polito.dp2.NFFG.sol3.service.jaxb.Nffg.Nodes createNffgNodes() {
        return new it.polito.dp2.NFFG.sol3.service.jaxb.Nffg.Nodes();
    }

    /**
     * Create an instance of {@link it.polito.dp2.NFFG.sol3.service.jaxb.Nffg.Links }
     * 
     */
    public it.polito.dp2.NFFG.sol3.service.jaxb.Nffg.Links createNffgLinks() {
        return new it.polito.dp2.NFFG.sol3.service.jaxb.Nffg.Links();
    }

    /**
     * Create an instance of {@link NamedEntities }
     * 
     */
    public NamedEntities createNamedEntities() {
        return new NamedEntities();
    }

    /**
     * Create an instance of {@link it.polito.dp2.NFFG.sol3.service.jaxb.Policy }
     * 
     */
    public it.polito.dp2.NFFG.sol3.service.jaxb.Policy createPolicy() {
        return new it.polito.dp2.NFFG.sol3.service.jaxb.Policy();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link Nffgs.Nffg.Nodes }
     * 
     */
    public Nffgs.Nffg.Nodes createNffgsNffgNodes() {
        return new Nffgs.Nffg.Nodes();
    }

    /**
     * Create an instance of {@link Nffgs.Nffg.Links }
     * 
     */
    public Nffgs.Nffg.Links createNffgsNffgLinks() {
        return new Nffgs.Nffg.Links();
    }

}
